apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-flask
  labels:
    name: hello-flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: hello-flask:latest
        ports:
        - containerPort: 5000